### ISSUE TITLE
YeelightSearch not working

### ISSUE THREAD

**Issue by Bastl34** [pmdroid/yeelight-wifi#23]
I'm using `YeelightSearch` to look up yeelights on my local network.
It does not find any light but I have one (RGBW E27 Smart LED Bulb) in my network. I can connect to it via telnet (on port 55443) 
What am I doing wrong? Or is something not working with the lookup?
Thanks

**Comment by pmdroid** [comment]
If you provide me your code I can have a look

**Comment by Bastl34** [comment]
Nothing special. Just:

```javascript
const yeelightSearch = new YeelightSearch();
yeelightSearch.on('found', (lightBulb) =>
{
    console.log(lightBulb);
});
```

`console.log` is never called

**Comment by pmdroid** [comment]
@Bastl34 
which platform and node version you are using?
is the yeelight connected to the same network?

**Comment by Bastl34** [comment]
I'm using the latest node LTS version on a Raspberry Pi and a Windows 10 PC. In both cases nothing is found. The yeelight is connected to my network and I can control it via the official Yeelight App (I also can connect to it via telnet as I said)

**Comment by pmdroid** [comment]
@Bastl34 sorry i've no idea what could be wrong.
i updated the node-ssdp maybe this fixes your problem

**Comment by Bastl34** [comment]
I've tried the new version.
It's working now.
Thanks :)
