### ISSUE TITLE
getValues() return always an empty array

### ISSUE THREAD

**Issue by Wifsimster** [pmdroid/yeelight-wifi#32]
I can't get any value returned from getValues() method.
I have E27 white and color bulb

```
light.getValues(["power"])
//return []
```

**Comment by mikemihu** [comment]
Hi @pmdroid is there any fix for this?

**Comment by Wifsimster** [comment]
Sadly, no. I still have the problem and can't find the problem in the code. Need to go deeper.

**Comment by Wifsimster** [comment]
@pmdroid : Ok, so i just look into it. It seems the getValues() promise is never resolved !

**Comment by pmdroid** [comment]
@Wifsimster  @mchaelhuang  sorry, i tried to debug this, but my time is limited right now

**Comment by pulento** [comment]
Just use
`light.getValues('power')`

see ff3ceb765157688e99b9a71ef8913d4b5c67b9bb

**Comment by Wifsimster** [comment]
Thanks, i'll try this !

**Comment by Wifsimster** [comment]
@pulento Still got `undefined` using a list instead of an array :/

```js
light.getValues('power') // promise return undefined
```

**Comment by pulento** [comment]
You'll not get anything on data. Because at code there is no parameter passed it just calls resolve().
Catch on event:

```
lightBulb.getValues('power', 'bright', 'rgb', 'color_mode',
                        'hue', 'sat', 'ct');

	lightBulb.on('response', (id, result) => {
        lightBulb['power'] = result[0];
        lightBulb['bright'] = result[1];
        lightBulb['rgb'] = result[2];
        lightBulb['color_mode'] = result[3];
        lightBulb['hue'] = result[4];
        lightBulb['sat'] = result[5];
        lightBulb['ct'] = result[6];
		debug(`power ${result[0]} and brightness ${result[1]} for request ${id}`);
	});
```
Check my fork also because I wasn't getting any notification until I patched some details at socket level.

**Comment by Wifsimster** [comment]
I remove my previous comment since your fork is not merge to this master, sorry.

@pulento Thanks for the sample, i just tried your fork, it's working well with your example, great work :+1: 

@pmdroid Merge with #50 will be greatly appreciated :)
